add_rules("mode.debug", "mode.release")

add_requires("nlohmann_json", "cpp-httplib", "boost", "openssl3", "vcpkg::webview2")
add_requireconfs("cpp-httplib", {configs = {ssl = true}})
add_requireconfs("boost", {configs = {all = true, header_only = true}})
add_requireconfs("*", {configs = {vs_runtime = "MD"}})

target("ms-login")
    set_kind("static")
    set_languages("clatest", "cxxlatest", {public = true})
    add_files("src/**.cpp|main.cpp")
    add_includedirs("src", {public = true})
    add_packages("nlohmann_json", "cpp-httplib", "boost", "openssl3", "vcpkg::webview2", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX")
    after_build(function (target)
        os.cp("$(projectdir)/src/webscript/browser_automation.js", path.directory(target:targetfile()))
    end)
